name: temperature_convertorchi
description: This is a simple super temperature convertor for the best developers in the world!
version: 1.0.0
repository: https://github.com/AkmaljonAbdirakhimov/temperature_convertorchi
homepage: https://github.com/AkmaljonAbdirakhimov/temperature_convertorchi

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

LICENSE: MIT
